apiVersion: apps/v1
kind: Deployment
metadata: 
  name: conv-temp-deployment
spec: 
  selector: 
    matchLabels:
      app: conversao-temperatura
  template: 
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conv-temp-container
        image: danielramost17/conversao-temperatura:latest
        ports: 
        - containerPort: 8080 # isso é necessário? porque na descricao do service é mostrado quais portas vao ser expostas pelos pods (em port: 8080)
---
apiVersion: v1
kind: Service
metadata:
  name: conv-temp-service
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080  # porta exposta em cada pod para o service, precisa ser 8080 porque a aplicacao (dentro do container) esta ouvindo essa porta
      nodePort: 30000  # porta que o service vai expor para usuarios poderem acessar a porta 8080 de cada pod
  type: NodePort
